# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [4]:
#Write your code here
import pandas as pd
df=pd.read_csv("E:\python\pandas\Pandas\Pandas Practice assignment\Data\Purchase_Data.csv")
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [5]:
#Write your code here
df.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [17]:
#Write you code here
result_1=df.loc[:,['invoice_number','invoice_time']]
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [20]:
#Write you code here
result_2=df.loc[0:2,:]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [22]:
#Write your code here
result_3=df.iloc[0:4,0:5]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [23]:
#Write your code here
result_4=df.loc[[0,4,6],['invoice_time','price']]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [24]:
number_rows=df.shape[0]
number_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [27]:
#Write your code here
result_5=df.loc[[number_rows-1]]
result_5

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [32]:
#Write your code here
avg_price=df['price'].mean()
max_price=df['price'].max()
avg_price
max_price

np.float64(6.01)

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [36]:
#Write you code here
avg_price_1,avg_num=df[['price','num_item']].mean()
avg_price_1,avg_num

(3.1920522110741363, 1.2983091787439613)

Create a column called "total", which is the product of the price and num_item columns.

In [41]:
#Write your code here
df['total']=df['price']*df['num_item']
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0

What is the avgerage price of the three most expensive purchases?

In [45]:
#Write your code here
avg_3=df['price'].nlargest(3).mean()
avg_3

np.float64(6.003333333333333)

How many different products are there?

In [48]:
#Write your code here
diff=df['product_id'].unique()
len(diff)

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [56]:
#Write your code here
t_mean=df['total'].describe()
diff_1=t_mean[1]-df['total'].median()
diff_1

C:\Users\COMPUMARTS\AppData\Local\Temp\ipykernel_5504\1931971973.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  diff_1=t_mean[1]-df['total'].median()

np.float64(0.9318078781127839)

Use the drop() method to delete the column total from the dataframe df_data.

In [57]:
#Write your code here
df.drop('total',axis=1)

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0
...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

Let's dig a little deeper into the data set and answer some basic question.

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [59]:
#Write your code here
df['invoice_time']=pd.to_datetime(df['invoice_time'])
df.dtypes

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
total                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [62]:
#Write your code here
df['dow']=df['invoice_time'].dt.day_of_week
df['monmth']=df['invoice_time'].dt.month
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total,dow,monmth
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,2.0,2,7
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2.0,2,7
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2.0,2,7
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,6.0,2,7
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,6.0,2,7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [64]:
#Write your code here
num_purchases_wed=df['dow'].value_counts()[2]
num_purchases_wed

np.int64(959)

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [66]:
#Write your code here
df_data=pd.read_csv('E:\python\pandas\Pandas\Pandas Practice assignment\Data\Titanic.csv')
df_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [71]:
#Write your code here
df_data.rename(columns={'Name':'Passenger_Name','Ticket':'Ticket_Num'},inplace=True)
df_data.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [89]:
#Write your code here
df_data.set_index('PassengerId' ,inplace=True)

Select the name of passenger 896

In [90]:
#Write your code here
df_data.loc[896, "Passenger_Name"]

'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [92]:
#Write your code here
df_data=df_data.reset_index(drop=False)
df_data

,index,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [100]:
#Write you code here
missing=df_data['Age'].isnull().sum()
print(missing)

86

Compute the avg age of passengers ignoring the missing data.

In [103]:
#Write your code here
avg_age=df_data['Age'].mean()
avg_age

np.float64(30.272590361445783)

Using the fillna() method replace the missing values in the Age column with the mean.

In [112]:
#Write your code here
df_data['Age']=df_data['Age'].fillna(df_data['Age'].mean())
df_data.head()

,index,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [114]:
#Write your code here
avg_oldest=df_data['Age'].nlargest(5).mean()
avg_oldest

np.float64(67.0)